spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true

        wall:
          enabled: true
          config:
            drop-table-allow: false

      aop-patterns: com.huang.admin.*

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        resetEnable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'




  jdbc:
    template:
      query-timeout: 3

#配置Mybatis规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    type: com.zaxxer.hikari.HikariDataSource